<a href="https://colab.research.google.com/github/Zeuqram07/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Exam

##### *Problem 1*

In [9]:
import numpy as np
A = np.array([[1,1,1],[1,0,4],[0,0,5]])
print(f'Matrix A:\n {A}')
print()
B = np.array ([[89],[89],[95]])
print(f'Matrix B:\n {A}')
C = np.linalg.inv(A).dot(B)
print(f'\nInverse of Matrix A:\n {C}')

Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix A:
 [[13.]
 [57.]
 [19.]]


##### *Problem 2*

In [10]:
import numpy as np
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(f'Matrix A:\n {A}')

#since it is a singular matrix, we cannot inverse it. However, we can still see the output if we use pinv
inv_A = np.linalg.pinv(A)
print(f'\inverse of Matrix A: \n{inv_A}')

B = np.array([[5],[10],[-20]])
print(f'Matrix A:\n {A}')

X = np.dot(inv_A, B)
print(f'\nDot product:\n {X}')

C = np.dot(A, X)
print(f'\nChecking:\n {C}')

Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
\inverse of Matrix A: 
[[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]]
Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Dot product:
 [[ 1.20629371]
 [-0.4020979 ]
 [ 0.4020979 ]]

Checking:
 [[  4.42307692]
 [ 13.26923077]
 [-17.69230769]]


##### *Problem 3*

In [7]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A, "\n")
W, V = np.linalg.eig(A)

print(" The eigenvalues are: \n" ,W)
print("\n The eigenvectors are: \n" ,V.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

 The eigenvalues are: 
 [-1.  3.  2.]

 The eigenvectors are: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
