<a href="https://colab.research.google.com/github/Zeuqram07/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse

In [5]:
import numpy as np
A = np.array([[1,2],[4,7]])
invA = (np.linalg.inv(A))
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [6]:
C=np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


In [8]:
import numpy as np
A = np.array([[2,3,4],[1,5,6],[8,9,1]])
B = (np.linalg.inv(A))
print (B)

[[ 0.60493827 -0.40740741  0.02469136]
 [-0.58024691  0.37037037  0.09876543]
 [ 0.38271605 -0.07407407 -0.08641975]]


Transpose:

In [7]:
##Python program to inverse a 3x3 Matrix A = ([2,3,4],[4,-2,6],[2,7,8])
A = np.array([[2,3,4],[4,-2,6],[2,7,8]])
print(A)
B = np.transpose(A)
print(B)

[[ 2  3  4]
 [ 4 -2  6]
 [ 2  7  8]]
[[ 2  4  2]
 [ 3 -2  7]
 [ 4  6  8]]
