<a href="https://colab.research.google.com/github/Zeuqram07/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practical Lab Exam 1

Problem 1. A

In [11]:
import numpy as np
#1A WY
W = np.array([[1,-3],[2,-2],[3,1]])
print("W =",W)

W = [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [12]:
Y = np.array([[1,2,0],[0,-1,2]])
print("Y =",Y)

Y = [[ 1  2  0]
 [ 0 -1  2]]


In [9]:
print(np.dot(W, Y))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


Problem 1. B

In [3]:
#1B Z+Z
Z = np.array([[0,1],[2,3]])
Z = np.array([[0,1],[2,3]])
print(Z+Z)

[[0 2]
 [4 6]]


Problem 1. C

In [17]:
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print("X =",X)
print()
print("Answer: ",3*X)

X = [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

Answer:  [[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem 2. A

In [22]:
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
print(np.dot(Y,W)^2)

[[ 7 -5]
 [ 6  6]]


Problem 2. B

In [25]:
R = np.dot(W,Y)
R

array([[ 1,  5, -6],
       [ 2,  6, -4],
       [ 3,  5,  2]])

In [26]:
print(np.subtract(R,X))

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


Problem 2. C

In [30]:
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
Z = np.array([[0,1],[2,3]])
print(np.dot(Y,W)-Z^2)

[[ 7 -6]
 [ 0  3]]
