<a href="https://colab.research.google.com/github/Zeuqram07/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

Answer for Question 1

In [9]:
import numpy as np

C= np.zeros((4,4)) # 4x4 matrix
np.fill_diagonal(C,1)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Answer for Question 2

In [8]:
import numpy as np

c = np.zeros((4,4)) # 4x4 matrix
np.fill_diagonal(c,1) # To fill a diagonal line with a given number, use the fill diagonal method. In this case number "1" is used.
print("c = ")
print(c)
print("Doubled: ")
print(2*c)

c = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Doubled: 
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Answer for Question 3

In [5]:
import numpy as np

A = np.array([2,7,4])
B = np.array([3,9,8])

cross = np.cross(A,B)
print(cross)

[20 -4 -3]
