<a href="https://colab.research.google.com/github/Zeuqram07/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector Space Operations

In [7]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [8]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1,ball2])
print(pool.shape)
print(pool.size)

(2, 3)
6


##Vector Addition

In [9]:
R = A+B
print(R)

[ 6 -2]


In [10]:
R = np.add(A,B)
R

array([ 6, -2])

##Vector Subtraction

In [11]:
R = np.subtract(A,B)
R

array([2, 8])

##Vector Scaling

In [12]:
A = np.array([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


In [13]:
S = np.multiply(5,A)
print(S)

[ 5 25 40 45]


#Vector Cross Product

In [25]:
#initialize arrays

A = np.array([2,7])
B = np.array([1,7])

#compute for the cross product

output = np.cross(A,B)
print(output)

7


In [26]:
#compute the dot product of A and B
output = np.dot(A,B)
print(output)

51
