<a href="https://colab.research.google.com/github/Zeuqram07/Linear-Algebra-58019/blob/main/Python%20Exercise%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operation

Vector Representation

In [5]:
#sum A + B
import numpy as np
A = np.array(([-5,0],[4,1]))
B = np.array(([6,-3],[2,3]))
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [7]:
#difference = A - B
A = np.array(([-5,0],[4,1]))
B = np.array(([6,-3],[2,3]))
print(A-B)

[[-11   3]
 [  2  -2]]


In [8]:
#difference2 = B - B
A = np.array(([6,-3],[2,3]))
B = np.array(([6,-3],[2,3]))
print(B-B)

[[0 0]
 [0 0]]
